#!/bin/bash

export BMUX_SESSION_NAME="aws"

tmuxb session

tmuxb window 1 "cloudformation" "$HOME/Programming/aws/cloudformation"
tmuxb window 2 "lambda" "$HOME/Programming/aws/lambda"

tmuxb pane 1 1 -v "$HOME/Programming/aws/cloudformation"
tmuxb pane 2 1 -v "$HOME/Programming/aws/lambda"

tmuxb focus

tmux select-layout -t "${BMUX_SESSION_NAME}":1.1 "${BMUX_CODE}"
tmux select-layout -t "${BMUX_SESSION_NAME}":2.1 "${BMUX_CODE}"
