require('indent_blankline').setup({
  show_current_context = true,
  show_first_indent_level = true,
  filetype_exclude = {
    'packer',
    'markdown',
    'help',
    'TelescopePrompt',
    'Trouble',
    '',
  },
  buftype_exclude = { 'terminal', 'nofile' },
  context_patterns = {
    'class',
    'function',
    'func_literal',
    'method',
    '^if',
    'while',
    'for',
    'with',
    'try',
    'except',
    'argument_list',
    'object',
    'element',
    'from',
    'dictionary',
    'tuple',
    'set',
    'list',
  },
  show_trailing_blankline_indent = false,
})

vim.wo.colorcolumn = '99999'
