#!/bin/sh

tmux new-session -s aws -d -n cloudformation -c "$HOME"
tmux send-keys -t aws:1.1 "cd $HOME/Programming/aws/cloudformation; clear" ENTER
tmux new-window -t aws:2 -n lambda -c "$HOME/Programming/aws/lambda"

cd "$HOME/Programming/aws/cloudformation"
tmux split-window -t aws:1.1 -v
tmux select-layout -t aws:1.1 "$BMUX_CODE"

cd "$HOME/Programming/aws/lambda"
tmux split-window -t aws:2.1 -v
tmux select-layout -t aws:2.1 "$BMUX_CODE"

tmux select-pane -t aws:1.1
tmux select-pane -t aws:2.1
tmux select-window -t aws:1
