#!/bin/sh

# init
tmux new-session -s aws -d -n fzfaws -c "$HOME/Programming/aws/fzf.aws"
tmux new-window -t aws:2 -n cloudformation -c "$HOME/Programming/aws/cloudformation"
tmux new-window -t aws:3 -n lambda -c "$HOME/Programming/aws/lambda"

# window fzfaws
cd "$HOME/Programming/aws/fzf.aws"
tmux split-window -t aws:1.1 -v
cd "$HOME/.config/fzfaws"
tmux split-window -t aws:1.2 -h
tmux send-keys -t aws:1.1 'source venv/bin/activate' ENTER
tmux send-keys -t aws:1.2 'source venv/bin/activate' ENTER
tmux send-keys -t aws:1.1 'clear' ENTER
tmux send-keys -t aws:1.2 'clear' ENTER
tmux select-layout -t aws:1.1 "$BMUX_3_VS"
# window cloudformation
cd "$HOME/Programming/aws/cloudformation"
tmux split-window -t aws:2.1 -h
# window lambda
cd "$HOME/Programming/aws/lambda"
tmux split-window -t aws:3.1 -h

# reset window
tmux select-pane -t aws:1.1
tmux select-pane -t aws:2.1
tmux select-pane -t aws:3.1
tmux select-window -t aws:1
