#!/bin/sh

tmux new-session -s mealternative -d -n frontend -c "$HOME"
tmux send-keys -t mealternative:1.1 "cd $HOME/Programming/web/mealternative-full-stack/mealternative; clear" ENTER
tmux new-window -t mealternative:2 -n backend -c "$HOME/Programming/web/mealternative-full-stack/backend-mealternative"

cd "$HOME/Programming/web/mealternative-full-stack/mealternative"
tmux split-window -t mealternative:1.1 -h
tmux split-window -t mealternative:1.2 -v
tmux select-layout -t mealternative:1.1 "$BMUX_3_WEB"

cd "$HOME/Programming/web/mealternative-full-stack/backend-mealternative"
tmux split-window -t mealternative:2.1 -h
tmux split-window -t mealternative:2.2 -v
tmux select-layout -t mealternative:2.1 "$BMUX_3_WEB"

tmux select-pane -t mealternative:1.1
tmux select-pane -t mealternative:2.1
tmux select-window -t mealternative:1
