#!/bin/sh

export BMUX_SESSION_NAME="nvim"

tmuxb session

tmuxb window 1 "init.lua" "$XDG_CONFIG_HOME/nvim"
tmuxb window 2 "close-buffers.nvim" "$HOME/Programming/lua/close-buffers.nvim"
tmuxb window 3 "conflict-marker.nvim" "$HOME/Programming/lua/conflict-marker.nvim"

tmuxb focus
