#!/bin/sh

tmux new-session -s python -d -n fzfaws -c "$HOME"
tmux send-keys -t python:1.1 "cd $HOME/Programming/python/fzf.aws; clear" ENTER
tmux new-window -t python:2 -n InquirerPy -c "$HOME/Programming/python/InquirerPy"

cd "$HOME/Programming/python/fzf.aws"
tmux split-window -t python:1.1 -v
cd "$HOME/.config/fzfaws"
tmux split-window -t python:1.2 -h
tmux send-keys -t python:1.1 'source venv/bin/activate; clear' ENTER
tmux send-keys -t python:1.2 'source venv/bin/activate; clear' ENTER
tmux select-layout -t python:1.1 "$BMUX_3_VS"

cd "$HOME/Programming/python/InquirerPy"
tmux split-window -t python:2.1 -v
cd "$HOME/Programming/docs/InquirerPy.wiki"
tmux split-window -t python:2.2 -h
tmux send-keys -t python:2.1 'source venv/bin/activate; clear' ENTER
tmux send-keys -t python:2.2 'source venv/bin/activate; clear' ENTER
tmux select-layout -t python:2.1 "$BMUX_3_VS"

tmux select-pane -t python:1.1
tmux select-pane -t python:2.1
tmux select-window -t python:1
