#!/bin/bash

export BMUX_SESSION_NAME="python"

tmuxb session

tmuxb window 1 "fzfaws" "$HOME/Programming/python/fzf.aws"
tmuxb window 2 "InquirerPy" "$HOME/Programming/python/InquirerPy"
tmuxb window 3 "s3fm" "$HOME/Programming/python/s3fm"
tmuxb window 4 "pfzy" "$HOME/Programming/python/pfzy"

tmuxb pane 1 1 -v "$HOME/Programming/python/fzf.aws"
tmuxb pane 2 1 -v "$HOME/Programming/python/InquirerPy"
tmuxb pane 3 1 -v "$HOME/Programming/python/s3fm"
tmuxb pane 4 1 -v "$HOME/Programming/python/pfzy"

for i in {1..4}; do
	tmuxb cmd "${i}" 1 "source venv/bin/activate"
	tmuxb cmd "${i}" 2 "source venv/bin/activate"
done

tmuxb focus

for i in {1..4}; do
	tmux select-layout -t "${BMUX_SESSION_NAME}":"${i}".1 "${BMUX_CODE}"
done
