#!/bin/sh

export BMUX_SESSION_NAME="shell"

tmuxb session

tmuxb window 1 "dotbare" "$HOME/Programming/shell/dotbare"
tmuxb window 2 "bmux" "$HOME/Programming/shell/bmux"
tmuxb window 3 "dump" "$HOME/Programming/shell/dump-cli"
tmuxb window 4 "scripts" "$HOME/Programming/scripts"

tmuxb pane 1 1 -v "$HOME/Programming/shell/dotbare"
tmuxb pane 2 1 -v "$HOME/Programming/shell/bmux"
tmuxb pane 3 1 -v "$HOME/Programming/shell/dump-cli"
tmuxb pane 4 1 -v "$HOME/Programming/scripts"

tmuxb focus

tmux select-layout -t "${BMUX_SESSION_NAME}":1.1 "${BMUX_CODE}"
tmux select-layout -t "${BMUX_SESSION_NAME}":2.1 "${BMUX_CODE}"
tmux select-layout -t "${BMUX_SESSION_NAME}":3.1 "${BMUX_CODE}"
tmux select-layout -t "${BMUX_SESSION_NAME}":4.1 "${BMUX_CODE}"
