#!/usr/bin/env sh

# -- mouse ---------------------------------------------------------------------

yabai -m config mouse_follows_focus off
yabai -m config focus_follows_mouse off
yabai -m config mouse_modifier fn
yabai -m config mouse_action1 resize
yabai -m config mouse_action2 move

# -- window -------------------------------------------------------------------

yabai -m config window_border on
yabai -m config window_border_width 1
yabai -m config window_border_radius 0
yabai -m config window_border_hidpi off
yabai -m config window_border_blur on
yabai -m config active_window_border_color 0x8081a1c1
yabai -m config normal_window_border_color 0x00ffffff
yabai -m config window_placement second_child
yabai -m config window_topmost on
yabai -m config window_shadow on
yabai -m config insert_feedback_color 0xaad75f5f
yabai -m config split_ratio 0.50
yabai -m config auto_balance off
yabai -m config window_opacity off
yabai -m config window_opacity_duration 0.0
yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 0.90

# -- space ---------------------------------------------------------------------

yabai -m config layout bsp
yabai -m config --space 1 layout float
yabai -m config --space 2 layout stack
yabai -m config top_padding 8
yabai -m config bottom_padding 8
yabai -m config left_padding 8
yabai -m config right_padding 8
yabai -m config external_bar main:34:0
yabai -m config window_gap 8

# -- rules ---------------------------------------------------------------------

yabai -m rule --add app="^Trello$" space=5
yabai -m rule --add app="^Slack$" space=6
yabai -m rule --add app="^Discord$" space=6
yabai -m rule --add app="^Microsoft\ Teams$" space=6
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^Firefox\ Developer\ Edition$" title="^Opening .*$" manage=off
yabai -m rule --add app="^Dictionary$" manage=off
yabai -m rule --add app="^Notes$" manage=off

echo "yabai configuration loaded.."
