#!/usr/bin/env sh
PLUGINS="$HOME/.config/sketchybar/plugins"

############## BAR ##############
sketchybar -m --bar height=25 \
	blur_radius=0 \
	position=top \
	padding_left=0 \
	padding_right=0 \
	margin=0 \
	corner_radius=0 \
	color=0x00000000 \
	border_width=0 \
	border_color=0xff2E3440 \
	display=main

############## GLOBAL DEFAULTS ##############
sketchybar -m --default updates=when_shown \
	drawing=on \
	cache_scripts=on \
	icon.font="MesloLGS Nerd Font Mono:Bold:16.0" \
	icon.color=0xffECEFF4 \
	icon.highlight_color=0xffA3BE8C \
	label.font="MesloLGS Nerd Font Mono:Bold:12.0" \
	label.color=0xffECEFF4

############## SPACE DEFAULTS ##############
sketchybar -m --default label.padding_left=0 \
	label.padding_right=0 \
	icon.padding_left=6 \
	icon.padding_right=6

############## PRIMARY DISPLAY SPACES ##############
sketchybar -m --add item logo left \
	--set logo icon= \
	background.color=0xffBF616A \
	background.corner_radius=4

sketchybar -m --add space home left \
	--set home associated_display=1 \
	associated_space=1 \
	icon= \
	icon.padding_left=9 \
	\
	--add space video left \
	--set video associated_display=1 \
	associated_space=2 \
	icon= \
	\
	--add space code left \
	--set code associated_display=1 \
	associated_space=3 \
	icon= \
	\
	--add space web left \
	--set web associated_display=1 \
	associated_space=4 \
	icon= \
	\
	--add space reserve left \
	--set reserve associated_display=1 \
	associated_space=5 \
	icon= \
	\
	--add space chat left \
	--set chat associated_display=1 \
	associated_space=6 \
	icon=

############## SECONDARY DISPLAY SPACES ##############
sketchybar -m --add space misc left \
	--set misc associated_display=2 \
	associated_space=7 \
	icon=

############## ITEM DEFAULTS ###############
sketchybar -m --default label.padding_left=0 \
	label.padding_right=0 \
	icon.padding_left=6 \
	icon.padding_right=6

############## RIGHT ITEMS ##############
sketchybar -m --add item date right \
	--set date \
	update_freq=60 \
	label.padding_right=6 \
	label.padding_left=0 \
	icon.padding_left=0 \
	icon.padding_right=3 \
	script="$PLUGINS/date.sh"

sketchybar -m --add item date_icon right \
	--set date_icon icon= \
	background.color=0xffBF616A \
	background.corner_radius=4

sketchybar -m --add item battery right \
	--set battery \
	update_freq=10 \
	label.padding_right=12 \
	script="$PLUGINS/battery.sh"

sketchybar -m --add item sound right \
	--set sound \
	update_freq=3 \
	script="$PLUGINS/volume.sh"

sketchybar -m --add item network right \
	--set network \
	update_freq=3 \
	script="$PLUGINS/network.sh"

sketchybar --add bracket primary_spaces \
	logo \
	home \
	video \
	code \
	web \
	reserve \
	chat \
	--set primary_spaces \
	background.color=0xff0c131f \
	background.border_color=0xffa062f6 \
	background.border_width=2 \
	background.corner_radius=4

sketchybar --add bracket _date \
	date \
	date_icon \
	--set _date \
	background.color=0xff0c131f \
	background.border_color=0xffa062f6 \
	background.border_width=2 \
	background.corner_radius=4

sketchybar -m --update

echo "sketchybar configuration loaded.."
