
[bell]
duration = 0

[colors]
draw_bold_text_with_bright_colors = false

[[colors.indexed_colors]]
color = "#2e3440"
index = 16

[[colors.indexed_colors]]
color = "#3b4252"
index = 17

[[colors.indexed_colors]]
color = "#434c5e"
index = 59

[[colors.indexed_colors]]
color = "#4c566a"
index = 60

[[colors.indexed_colors]]
color = "#d8dee9"
index = 69

[[colors.indexed_colors]]
color = "#e5e9f0"
index = 73

[[colors.indexed_colors]]
color = "#eceff4"
index = 75

[[colors.indexed_colors]]
color = "#8fbcbb"
index = 81

[[colors.indexed_colors]]
color = "#88c0d0"
index = 102

[[colors.indexed_colors]]
color = "#81a1c1"
index = 114

[[colors.indexed_colors]]
color = "#5e81ac"
index = 130

[[colors.indexed_colors]]
color = "#2e3440"
index = 145

[[colors.indexed_colors]]
color = "#bf616a"
index = 168

[[colors.indexed_colors]]
color = "#d08770"
index = 173

[[colors.indexed_colors]]
color = "#ebcb8b"
index = 176

[[colors.indexed_colors]]
color = "#a3be8c"
index = 180

[[colors.indexed_colors]]
color = "#b48ead"
index = 233

[colors.bright]
black = "#4c566a"
blue = "#81a1c1"
cyan = "#8fbcbb"
green = "#a3be8c"
magenta = "#b48ead"
red = "#bf616a"
white = "#eceff4"
yellow = "#ebcb8b"

[colors.cursor]
cursor = "#d8dee9"
text = "#2e3440"

[colors.dim]
black = "#373e4d"
blue = "#68809a"
cyan = "#6d96a5"
green = "#809575"
magenta = "#8c738c"
red = "#94545d"
white = "#aeb3bb"
yellow = "#b29e75"

[colors.normal]
black = "#3b4252"
blue = "#81a1c1"
cyan = "#88c0d0"
green = "#a3be8c"
magenta = "#b48ead"
red = "#bf616a"
white = "#e5e9f0"
yellow = "#ebcb8b"

[colors.primary]
background = "#2e3440"
dim_foreground = "#a5abb6"
foreground = "#d8dee9"

[colors.search.focused_match]
background = "#434c5e"
foreground = "#d8dee9"

[colors.search.matches]
background = "#88c0d0"
foreground = "CellBackground"

[colors.selection]
background = "#4c566a"
text = "CellForeground"

[colors.vi_mode_cursor]
cursor = "#d8dee9"
text = "#2e3440"

[cursor]
style = "Block"
unfocused_hollow = true
vi_mode_style = "None"

[debug]
log_level = "Warn"
persistent_logging = false
print_events = false
render_timer = false

[font]
size = 14.5

[font.glyph_offset]
x = 0
y = 0

[font.normal]
family = "MesloLGS Nerd Font Mono"

[font.offset]
x = 0
y = 0

[hints]
alphabet = "jfkdls;ahgurieowpq"

[[hints.enabled]]
command = "open"
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.binding]
key = "U"
mods = "Control|Shift"

[hints.enabled.mouse]
enabled = true
mods = "command"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "PageUp"

[[keyboard.bindings]]
chars = "\u001B[5~"
key = "PageUp"
mode = "Alt"

[[keyboard.bindings]]
chars = "\u001B[5~"
key = "PageUp"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "PageDown"

[[keyboard.bindings]]
chars = "\u001B[6~"
key = "PageDown"
mode = "Alt"

[[keyboard.bindings]]
chars = "\u001B[6~"
key = "PageDown"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToTop"
key = "Home"

[[keyboard.bindings]]
chars = "\u001BOH"
key = "Home"
mode = "Alt"

[[keyboard.bindings]]
chars = "\u001B[H"
key = "Home"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "End"

[[keyboard.bindings]]
chars = "\u001BOF"
key = "End"
mode = "Alt"

[[keyboard.bindings]]
chars = "\u001B[F"
key = "End"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B\t"
key = "Tab"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B\u001B[Z"
key = "Tab"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u007F"
key = "Back"

[[keyboard.bindings]]
chars = "\u001B\u007F"
key = "Back"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B\b"
key = "Back"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u0000"
key = "Space"
mods = "Control"

[[keyboard.bindings]]
chars = " "
key = "Space"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bb"
key = "Left"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B\u001B[D"
key = "Left"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B\u001B[C"
key = "Right"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B\u001B[B"
key = "Down"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B\u001B[B"
key = "Down"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "\u001B\u001B[A"
key = "Up"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B\u001B[A"
key = "Up"
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = """
:w
"""
key = "S"
mods = "Command"

[[keyboard.bindings]]
chars = """
:CtrlSemicolumn
"""
key = "Semicolon"
mods = "Command"

[[keyboard.bindings]]
chars = """
:CtrlColumn
"""
key = "Comma"
mods = "Command"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Command"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Command"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Command"

[[keyboard.bindings]]
action = "ClearHistory"
key = "K"
mods = "Command"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Command"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Command"

[[keyboard.bindings]]
action = "Hide"
key = "H"
mods = "Command"

[[keyboard.bindings]]
action = "Minimize"
key = "M"
mods = "Command"

[[keyboard.bindings]]
action = "Quit"
key = "Q"
mods = "Command"

[[keyboard.bindings]]
action = "Quit"
key = "W"
mods = "Command"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Command"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "Return"
mods = "Command"

[mouse]
hide_when_typing = true

[scrolling]
history = 0
multiplier = 3

[selection]
save_to_clipboard = false
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[terminal.shell]
program = "/bin/zsh"

[window]
decorations = "none"
dynamic_padding = true
dynamic_title = false
opacity = 1.0
option_as_alt = "Both"
startup_mode = "Windowed"
title = "Alacritty"

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 1
y = 0

[window.position]
x = 0
y = 0

[general]
live_config_reload = true
working_directory = "None"

[terminal]
