import shutil

import ranger.api
from ranger.core.linemode import LinemodeBase

extension_maps = {
    "7z": "",
    "gz": "",
    "jar": "",
    "zip": "",
    "xz": "",
    "tar": "",
    "taz": "",
    "gruntfile": "",
    "gulpfile": "",
    "dropbox": "",
    "xls": "",
    "doc": "",
    "ppt": "",
    "xml": "",
    "webpack": "ﰩ",
    ".settings.json": "",
    "cs": "",
    "procfile": "",
    "svg": "ﰟ",
    ".bashprofile": "",
    ".bashrc": "",
    ".babelrc": "ﬥ",
    ".ds_store": "",
    "git": "",
    ".gitattributes": "",
    ".gitconfig": "",
    ".gitignore": "",
    ".gitmodules": "",
    "COMMIT_EDITMSG": "",
    "COPYING": "",
    "COPYING.LESSER": "",
    ".gitlab-ci.yml": "",
    ".gvimrc": "",
    ".npmignore": "",
    ".vimrc": "",
    ".zshrc": "",
    ".zshenv": "",
    ".zprofile": "",
    "Dockerfile": "",
    "Gemfile$": "",
    "LICENSE": "",
    "Vagrantfile$": "",
    "_gvimrc": "",
    "_vimrc": "",
    "ai": "",
    "awk": "",
    "bash": "",
    "bat": "",
    "bmp": "",
    "c": "",
    "c++": "",
    "cc": "",
    "clj": "",
    "cljc": "",
    "cljs": "",
    "CMakeLists.txt": "",
    "cmake": "",
    "coffee": "",
    "conf": "",
    "config.ru": "",
    "cp": "",
    "cpp": "",
    "csh": "",
    "cson": "",
    "css": "",
    "cxx": "",
    "d": "",
    "dart": "",
    "db": "",
    "diff": "",
    "dockerfile": "",
    "dump": "",
    "edn": "",
    "eex": "",
    "ejs": "",
    "elm": "",
    "erl": "",
    "ex": "",
    "exs": "",
    "f#": "",
    "favicon.ico": "",
    "fish": "",
    "fs": "",
    "fsi": "",
    "fsscript": "",
    "fsx": "",
    "gemspec": "",
    "gif": "",
    "go": "",
    "h": "",
    "haml": "",
    "hbs": "",
    "hh": "",
    "hpp": "",
    "hrl": "",
    "hs": "",
    "htm": "",
    "html": "",
    "erb": "",
    "hxx": "",
    "ico": "",
    "ini": "",
    "java": "",
    "jl": "",
    "jpeg": "",
    "jpg": "",
    "js": "",
    "json": "",
    "jsx": "",
    "ksh": "",
    "leex": "",
    "less": "",
    "lhs": "",
    "license": "",
    "lua": "",
    "makefile": "",
    "markdown": "",
    "md": "",
    "mdx": "",
    "mix.lock": "",
    "mjs": "",
    "ml": "λ",
    "mli": "λ",
    "mustache": "",
    "nix": "",
    "node_modules": "",
    "php": "",
    "pl": "",
    "pm": "",
    "png": "",
    "pp": "",
    "ps1": "",
    "psb": "",
    "psd": "",
    "py": "",
    "pyc": "",
    "pyd": "",
    "pyo": "",
    "r": "ﳒ",
    "R": "ﳒ",
    "rake": "",
    "rakefile": "",
    "rb": "",
    "rlib": "",
    "rmd": "",
    "Rmd": "",
    "rs": "",
    "rss": "",
    "sass": "",
    "scala": "",
    "scss": "",
    "sh": "",
    "slim": "",
    "sln": "",
    "sql": "",
    "styl": "",
    "suo": "",
    "swift": "",
    "t": "",
    "tex": "ﭨ",
    "toml": "",
    "ts": "",
    "tsx": "",
    "twig": "",
    "vim": "",
    "vue": "﵂",
    "webmanifest": "",
    "webp": "",
    "xcplayground": "",
    "xul": "",
    "yaml": "",
    "yml": "",
    "zsh": "",
    "terminal": "",
    "pdf": "",
    "kt": "𝙆",
    "gd": "",
    "tscn": "",
    "godot": "",
    "tres": "",
    "glb": "",
    "import": "",
    "material": "",
    "otf": "",
    "cfg": "",
    "pck": "",
    "desktop": "",
    "opus": "",
    "svelte": "",
}

exact_maps = {
    ".config": "",
    ".git": "",
    "Downloads": "",
    "Pictures": "",
    "TempScreenShot": "",
    "Documents": "",
    "node_modules": "",
    ".DS_Store": "",
    ".gitignore": "",
    ".gitconfig": "",
    "Dockerfile": "",
    "docker-compose.yml": "",
    ".vimrc": "",
    ".viminfo": "",
    "init.vim": "",
}


@ranger.api.register_linemode
class NerdIconsLinemode(LinemodeBase):
    name = "nerdicons"

    uses_metadata = False

    def filetitle(self, file, metadata):
        if file.is_directory:
            icon = exact_maps.get(file.relative_path, "")
        elif file.is_link:
            icon = ""
        elif "x-python" in file.filetype:
            icon = ""
        elif shutil.which(file.path):
            icon = ""
        else:
            icon = exact_maps.get(
                file.relative_path, extension_maps.get(file.extension, "")
            )
        return icon + " " + file.relative_path
